### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [109]:
# np.array
import numpy as np  

a = np.array([1,2,3])
print(a)

[1 2 3]


In [110]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [111]:
import numpy as a

arr = a.array([[1,2,3,4], [6,7,8,9], [2,6,7,9]])
print(arr)

[[1 2 3 4]
 [6 7 8 9]
 [2 6 7 9]]


In [112]:
print(arr[1,2])

8


In [113]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [114]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [115]:
new= np.array([1,33,5,5], dtype=complex)
print(new)

[ 1.+0.j 33.+0.j  5.+0.j  5.+0.j]


In [116]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [117]:
a= np.arange(1,13).reshape(4,3)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [118]:
r = np.arange(15).reshape(5,3)
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [119]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [120]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [121]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
# np.random
np.random.random((3,4))

array([[0.55264009, 0.14425635, 0.37746862, 0.14285842],
       [0.05429453, 0.141495  , 0.14550865, 0.12341291],
       [0.01395748, 0.0365925 , 0.11826071, 0.00890708]])

In [123]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [124]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [125]:
np.random.random((5,5))

array([[0.28824508, 0.36331094, 0.21195127, 0.55478445, 0.42108927],
       [0.07394771, 0.26136198, 0.76247312, 0.07311574, 0.43711127],
       [0.09560267, 0.61830244, 0.91166665, 0.47044879, 0.32684816],
       [0.23285331, 0.73475246, 0.80416004, 0.43684915, 0.00896095],
       [0.03573578, 0.4458443 , 0.92062606, 0.79452431, 0.39281892]])

In [126]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [127]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [128]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [129]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [130]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [131]:
# ndim
a3.ndim

3

In [132]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [133]:
a3.shape

(2, 2, 2)

In [134]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [135]:
a1.size

10

In [136]:
# itemsize
# tells int32 and int64 bit size

a1.itemsize

4

In [137]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


In [138]:
a1.dtype

dtype('int32')

### Changing Datatype

In [139]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [140]:
arr1 = np.arange(1,13, dtype=float)
arr1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [141]:
arr1.astype(np.int32)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)

In [142]:
arr1.dtype

dtype('float64')

### Array Operations

In [143]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [144]:
# scalar operations

# arithmetic
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [145]:
a1-1

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [146]:
# relational
a2 >15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [147]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [148]:
a2 == 12

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [149]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [150]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### Array Functions

In [151]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[25., 24., 22.],
       [87., 37., 20.],
       [43.,  9., 20.]])

In [152]:
a22 = np.random.random((3,3))
a22 = np.round(a22*100)
a22

array([[17.,  7., 22.],
       [24., 91., 68.],
       [38., 93., 92.]])

In [153]:
print(np.max(a22))
print(np.min(a22))
print(np.sum(a22))
print(np.prod(a22))

93.0
7.0
452.0
126411202165248.0


In [154]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([93525.,  7992.,  8800.])

In [155]:
# mean/median/std/var
np.var(a1,axis=1)

array([  1.55555556, 808.66666667, 200.66666667])

In [156]:
# trigonomoetric functions
np.sin(a1)

array([[-0.13235175, -0.90557836, -0.00885131],
       [-0.82181784, -0.64353813,  0.91294525],
       [-0.83177474,  0.41211849,  0.91294525]])

In [157]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [158]:
# log and exponents
np.exp(a1)

array([[7.20048993e+10, 2.64891221e+10, 3.58491285e+09],
       [6.07603023e+37, 1.17191424e+16, 4.85165195e+08],
       [4.72783947e+18, 8.10308393e+03, 4.85165195e+08]])

In [159]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[78.,  9., 40.],
       [19., 66., 44.]])

In [160]:
a23 = np.arange(12).reshape(3,4)
a23

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [161]:
new_a23 = a23*3.1
new_a23

array([[ 0. ,  3.1,  6.2,  9.3],
       [12.4, 15.5, 18.6, 21.7],
       [24.8, 27.9, 31. , 34.1]])

In [162]:
np.round(new_a23)

array([[ 0.,  3.,  6.,  9.],
       [12., 16., 19., 22.],
       [25., 28., 31., 34.]])

In [163]:
np.floor(new_a23)

array([[ 0.,  3.,  6.,  9.],
       [12., 15., 18., 21.],
       [24., 27., 31., 34.]])

In [164]:
np.ceil(new_a23)

array([[ 0.,  4.,  7., 10.],
       [13., 16., 19., 22.],
       [25., 28., 31., 35.]])

### Indexing and Slicing

In [165]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [166]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [168]:
a2[1,0]

np.int64(4)

In [169]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [170]:
a3[1,0,1]

np.int64(5)

In [171]:
a3[1,1,0]

np.int64(6)

In [172]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [173]:
a1[2:5:2]

array([2, 4])

In [174]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# to get ans of below question just ask yourself which row you want and which column you want

In [202]:
# extract first row
a2[0,:]

array([0, 1, 2, 3])

In [203]:
# extract first column
a2[:,0]

array([0, 4, 8])

In [210]:
#extract 2nd colum
a2[:,1]

array([1, 5, 9])

In [211]:
#extract 2nd row
a2[1:,]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [216]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [217]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [213]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [177]:
a2[1,::3]

array([4, 7])

In [178]:
a2[0,:]

array([0, 1, 2, 3])

In [179]:
a2[:,2]

array([ 2,  6, 10])

In [180]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [224]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [228]:
a3[0,1,:]

array([3, 4, 5])

In [182]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [183]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [184]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [185]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(a1):
    print(i)

In [186]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [187]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [188]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [189]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [190]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [191]:
# reshape

In [192]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [193]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [194]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [195]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [196]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [197]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [198]:
np.hsplit(a4,5)

ValueError: array split does not result in an equal division

In [ ]:
# vertical splitting

In [ ]:
a5

In [ ]:
np.vsplit(a5,2)